# Site settings
author: organized-cache-5087
title: 
header-img: img/home-bg.png
email: geoff.puttkammer@gmail.com
copyright_name: organized-cache-5087
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  geoffputt88

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
